services:
  db:
    image: postgres:15-alpine
    container_name: spring_postgres
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev123}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
